site_name: Master MkDocs
docs_dir: 'docs'


theme:
  name: material  # MkDocs for Materialに表示スタイルを切替.
  language: ja    # メニュー言語を日本語に変更.
  icon:           # サイト名横のアイコン画像を変更.
    logo: material/school
    repo: fontawesome/brands/git-alt
  favicon: images/favicon.png  # ファビコン画像の設定.
  features:
    - tabs   # タブ表示を有効化.


markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - toc:
        permalink: true
    - fontawesome_markdown


extra_css:
    # ユーザー個別で効かせたい設定を記述.
    - css/custom.css
    # fontawesome_markdownで使える設定を別途追加.
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"


# Copyright
copyright: 'Copyright © 2010 - 2020 - Classmethod, Inc.'
