on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install pipenv
      # - run: python -m pipenv sync --dev
      # - run: python -m pipenv sync
      - run: pyhton -m pip install mkdocs
      - run: python -m pipenv run mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: github-user-name/github-repository-name
          publish_branch: master
          publish_dir: ./site
