name: Deploy mkdocs

# on:
# pull_request:
    # PRのcloseをトリガーとしてjobを実行する
#    branches:
#      - master
#    types:
#      - closed
on: [push]

env:
  s3-bucket: test-20211105-99 


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout branch 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #- name: configure git info
      #  run: |
      #    git config --global user.name "github-actions-for-deploy"
      #    git config --global user.email deploy-actions@github.com

      #- name: check git status/branch
      #  run: |
      #    git status
      #    git branch


      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: echo $BRANCH_NAME


      # mkdocsを利用するためのpython環境のセットアップ
      - name: setup python env
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ドキュメントの作成
      - name: mkdocs build
        run: |
           mkdocs build --verbose --clean --strict


      - name: Set current datetime as env variable
        # env:
        #  TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Show current datetime
        run: echo ${{ env.CURRENT_DATETIME }}


      - name: List files in the repository
        run: |
          ls -ltrR ${{ github.workspace }}

      # ドキュメントのデプロイ
      #- name: mkdocs deploy
      #  uses: peaceiris/actions-gh-pages@v3
        # uses: peaceiris/deploy_test@v3
      #  with:
      #     github_token: ${{ secrets.PERSONAL_TOKEN }}
      #     publish_dir: site
           
      # Slackでの通知
      #- name: notify slack
      #  uses: 8398a7/action-slack@v3
      #  if: always()
      #  with:
      #    status: ${{ job.status }}
      #    fields: repo,message,commit,author,action,eventName,ref,workflow  
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


      - name: Check to S3
        #-- GitHub上に登録した変数を持ってくる --#
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #-- 仮想マシン上でコマンドを実行 --#

        if [[ $(aws s3 ls s3://${{ env.s3-bucket }}/  | wc -l) > 0 ]]; then
        run: echo "AAAAAAAAAAAAAAAAAA"

      - name: Deploy to S3
        run:
          aws s3 sync --delete --region ap-northeast-1 ./site/ s3://test-20211105-99/
