name: Deploy mkdocs

on: [push]

env:
  s3-bucket: test-20211105-99 
  s3-dir: main 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout branch 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: echo $BRANCH_NAME

      # mkdocsを利用するためのpython環境のセットアップ
      - name: setup python env
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ドキュメントの作成
      - name: mkdocs build
        run: |
           mkdocs build --verbose --clean --strict


      - name: Check to S3
        run: |

          #aws s3 mb --region ap-northeast-1 s3://test-20211105-101
          if [[ $(aws s3 ls s3://${{ env.s3-bucket }} | wc -l) == 0 ]]; then
            aws s3 mb --region ap-northeast-1 s3://test-20211105-99
          fi

      - name: Deploy to S3
        run:
          # aws s3 sync --delete --region ap-northeast-1 ./site/ s3://test-20211105-99/
          aws s3 sync --delete --region ap-northeast-1 ./site/ s3://test-20211105-99/main/
